name: Update

on:
  watch:
    types: [started]
  schedule:
    - cron: "45 * * * *"
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure Origin
      uses: Boostport/setup-cloudflare-warp@v1
      with: 
        organization: ${{ secrets.CLOUDFLARE_ORGANIZATION }}
        auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
        auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install httpx uvloop 
    
    - name: Build
      run: |
        python ${{ github.workspace }}/run/ddt.py
    
    - name: Archive output
      run: |
        cd ${{ github.workspace }}
        zip -r lyrics.zip run/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lyric
        path: ${{ github.workspace }}/lyrics.zip